---
- name: Ensure dotfiles are copied to the home directory.
  template:
    src: "./files/dotfiles/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    variable_end_string: "ƒƒƒ"
    variable_start_string: "ƒƒƒ"
  with_items: "{{ dotfiles_files }}"
  become: no
